peridot: vintf: Declare Some Missing Hals In FCM
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.lineage.health.IChargingControl/default (@2)
    vendor.lineage.health.IFastCharge/default (@2)
    vendor.lineage.touch.IHighTouchPollingRate/default (@1)

Signed-off-by: Shikhar <Krtonia@gmail.com>